### ISSUE TITLE
ORCID logo disrupts spacing between lines

### ISSUE THREAD

**Issue by VitorAguiar** [curvenote/pubmatter#2]
Hello,

thanks for developing this library!

I'm using the author block as in your example "You can also use a dictionary directly", and the ORCID logo looks higher than the text (capital letters and affiliation superscripts). In a multi-line author list, that affects the spacing between lines and therefore lines with and without ORCID will have different spacing. 

Is there a way to avoid this?

Thank you!

**Comment by rowanc1** [comment]
There is the "baseline" variable that you can paste to the orcid logo:

https://github.com/typst/packages/blob/0d68bc5d575f9ee12eb931092c8dc278e998190e/packages/preview/scienceicons/0.0.6/index.typ#L111

I don't think that is exposed through this package, perhaps if you fix it here we can re-publish! That would require passing the baseline variable in here:

https://github.com/curvenote/pubmatter/blob/5f7296fff888a2a72f8d17a4c9520257f2314e71/pubmatter.typ#L26

**Comment by rowanc1** [comment]
You can also change the scale to be `1`, currrently it is 1.1, which might be the thing that is actually changing the lineheight. If you find a better way to position the icons, but not effect the line height, that would be useful to bring all the way down into scienceicons.
